### ISSUE TITLE
loraserver.io Authentication

### ISSUE THREAD

**Issue by 1995parham** [I1820/sjd-backend#3]
LoRa Authentication sometimes fails and returns token expires error.

**Comment by 1995parham** [comment]
End is near 💀

**Comment by 1995parham** [comment]
This needs serious attention 😞

**Comment by sajjadrahnama7** [comment]
I’ll check it ASAP.

**Comment by 1995parham** [comment]
@sajjadrahnama7 Shit! I do not think this is going to send you a mail. I am so sorry. The project has stopped since the summer. I want to restore it and lunch it on our servers in CEIT for remembering our great work.

**Comment by 1995parham** [comment]
💃 💃 it is fixed
